name: Build and Push forgejo-runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC

jobs:
  build-and-push:
    runs-on: forgejo-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Extract metadata
        id: meta
        run: |
          # We only need to calculate the SHA and Date now.
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          # Replaced output.inc_tag with forgejo.run_number
          docker build \
            -t networklessons/lab-node-ubuntu:latest \
            -t networklessons/lab-node-ubuntu:${{ forgejo.run_number }}

      - name: Push Docker image
        run: |
          # Replaced output.inc_tag with forgejo.run_number
          docker push networklessons/lab-node-ubuntu:latest
          docker push networklessons/lab-node-ubuntu:${{ forgejo.run_number }}
