name: Publish Docker image

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual trigger from GitHub website
  push:
    branches: 
      - main # Trigger the workflow on pushes to the main branch
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_NWL_USERNAME }}
          password: ${{ secrets.DOCKERHUB_NWL_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: networklessons/ubuntu-network-host
          # This will not be used directly for tagging in this scenario, but kept for potential label use.

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: networklessons/ubuntu-network-host-${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}
