name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/sync-readme-docker-hub.yml
  workflow_dispatch: # Allows manual trigger from GitHub website
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_NWL_USERNAME }}
        password: ${{ secrets.DOCKERHUB_NWL_PAT }}
        repository: networklessons/lab-node-ubuntu
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
